name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies by pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: |
            - recursive: true
              args: [--shamefully-hoist]

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Build
        run: npm run generate

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: gh-pages
          build_dir: ./.output/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
